development:
  adapter: postgresql
  encoding: utf-8
  database: starbus_development
  pool: 5
  username: toolmaker
  password:

test: &test
  adapter: postgresql
  encoding: utf-8
  database: starbus_test
  pool: 5
  username: toolmaker
  password:

production:
