development:
  adapter: postgresql
  encoding: utf-8
  database: starbus_development
  pool: 5
  username: toolmaker
  password:

test: &test
  adapter: postgresql
  encoding: utf-8
  database: starbus_test
  pool: 5
  username: toolmaker
  password:

production:
  adapter: postgresql
  encoding: utf-8
  database: d33ph7u6vr2csa
  username: gojcusdoicdnlj
  password: FWTKx8QaOl_CFaOKXRZDTHapHZ
  host: ec2-23-21-148-9.compute-1.amazonaws.com
  port: 5432
