development:
  adapter: postgresql
  host: localhost
  encoding: utf-8
  database: starbus-api #starbus_development
  pool: 5
  username: postgres
  password:

test: &test
  adapter: postgresql
  host: localhost
  encoding: utf-8
  database: starbus_test
  pool: 5
  username: toolmaker
  password:

production:
